require: rubocop-rspec

AllCops:
  DisplayCopNames: true

# コメントは日本語も書く
AsciiComments:
  Enabled: false

# top-lovelコメントは義務ではない
Style/Documentation:
  Enabled: false

# gemなのでハイフンも許可したい
Style/FileName:
  Enabled: false

# 横は120文字までOK
Metrics/LineLength:
  Max: 120

# メソッド10行の初期設定は厳しすぎるので15行に延長
# 複雑さを増やしていないのでメソッドの長さからコメントは除外
Metrics/MethodLength:
  Max: 15
  CountComments: false

# Ruby 2.3系から全部のファイルで出るようになった
# http://www.task-notes.com/entry/20160831/1472572735
# frozen string literal comment は使いたい機能だが、
# あまりにも不便すぎるので3.0でデフォルトになってからで
# 良いと思う。
Style/FrozenStringLiteralComment:
  Enabled: false

# ifやunlessを使うより先にguard節を使うべき、という指導
# Controllerのvalidationで避けられない場合があるので4行まで延長。
# 以下ならセーフ
# if form.invalid?
#   @form = form
#   flash[:error] = message
#   render :page
# end
# http://qiita.com/tbpgr/items/69c3830586fbe555b374
Style/GuardClause:
  MinBodyLength: 4

# デフォルト値は5。もうちょっとだけ複雑なexampleを書きたい。
RSpec/ExampleLength:
  Max: 6

# allow_any_instance_ofを使ってはいけない、というルール
# shared_contextで事前に設定ができなくなるので却下
RSpec/AnyInstance:
  Enabled: false

# いまどき末尾カンマは許可しないとダメでしょ
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false

# gemなので命名規約にうるさくしないでほしい
RSpec/FilePath:
  Enabled: false

# 長いテストケースを許容
RSpec/ExampleLength:
  Enabled: false
